# Generated by Django 3.0.1 on 2022-06-05 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0003_auto_20220605_0854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_code', models.CharField(max_length=125, verbose_name='کد پرواز')),
                ('flight_class', models.CharField(blank=True, max_length=125)),
                ('flight_no', models.CharField(blank=True, max_length=125)),
                ('source', models.CharField(max_length=125, verbose_name='مبذا')),
                ('target', models.CharField(max_length=125, verbose_name='مقصد')),
                ('date', models.CharField(max_length=125, verbose_name='تاریخ')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=125, verbose_name='شماره تماس')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('pnr_code', models.CharField(blank=True, max_length=125, verbose_name='شناسه رزرو')),
                ('air_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_line_reservation', to='airlines.Airline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=125)),
                ('en_family', models.CharField(max_length=125, verbose_name='نام لایتن')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=12, verbose_name='جنسیت')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('ir_name', models.CharField(max_length=125, verbose_name='نام')),
                ('ir_family', models.CharField(max_length=125, verbose_name='نام خانوادگی')),
                ('date', models.CharField(max_length=125)),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('age', models.CharField(max_length=125, verbose_name='سن')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='passangers.Reservation', verbose_name='رزرو کننده')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافر ها',
            },
        ),
    ]
