# Generated by Django 3.0.1 on 2022-06-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220607_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Image_Doc',
        ),
    ]
