# Generated by Django 3.0.1 on 2022-06-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_alter_reservehotel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservehotel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
