# Generated by Django 3.0.1 on 2022-06-03 12:11

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import accounts.uitils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(max_length=125, verbose_name="نام ")),
                (
                    "last_name",
                    models.CharField(max_length=125, verbose_name="نام خانوادگی"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=125, unique=True, verbose_name=""),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تلفن"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_admin", models.BooleanField(default=False, verbose_name="ادمین")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تماس"),
                ),
                ("code", models.PositiveSmallIntegerField(verbose_name="کد ارسالی")),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "کد  ارسالی",
                "verbose_name_plural": "کد های ارسالی",
            },
        ),
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "national_card",
                    models.ImageField(
                        upload_to=accounts.uitils.get_file_path,
                        verbose_name="تصویر کد ملی",
                    ),
                ),
                (
                    "identity_card",
                    models.ImageField(
                        upload_to=accounts.uitils.get_file_path,
                        verbose_name="تصویر شناسنامه",
                    ),
                ),
                (
                    "passport",
                    models.ImageField(
                        blank=True,
                        upload_to=accounts.uitils.get_file_path,
                        verbose_name="تصویر پاسپورت",
                    ),
                ),
                (
                    "other",
                    models.ImageField(
                        blank=True,
                        upload_to=accounts.uitils.get_file_path,
                        verbose_name="سایر مدارک",
                    ),
                ),
                ("bind", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرک",
                "verbose_name_plural": "مدارک",
            },
        ),
    ]
