# Generated by Django 3.0.1 on 2022-06-03 12:05

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="نام شرکت هواپیمایی "
                    ),
                ),
                ("symbol", models.CharField(max_length=10, verbose_name="نماد")),
                ("logo", models.ImageField(upload_to="", verbose_name="لوگو")),
                ("base_url", models.URLField()),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=125, verbose_name="نام کاربری"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=125, verbose_name="رمز عبور"
                    ),
                ),
            ],
            options={
                "verbose_name": "ایرلاین",
                "verbose_name_plural": "ایرلاین ها",
            },
        ),
    ]
